### ISSUE TITLE
如何构建自己的数据集

### ISSUE THREAD

**Issue by shangchengPKU** [ashawkey/CCNeRF#3]
您好，我尝试在自己构建的数据集上进行测试，但是我通过instant-ngp的提供的转换方式进行转换得到transform.json之后发现无法使用，
Traceback (most recent call last):
  File "train.py", line 306, in <module>
    reconstruction(args)
  File "train.py", line 113, in reconstruction
    test_dataset = dataset(args.datadir, split='test', downsample=args.downsample_train, is_stack=True)
  File "/home/11/CCNeRF/dataLoader/blender.py", line 25, in __init__
    self.read_meta()
  File "/home/11/CCNeRF/dataLoader/blender.py", line 95, in read_meta
    self.all_rgbs = torch.stack(self.all_rgbs, 0).reshape(-1,*self.img_wh[::-1], 3)  # (len(self.meta['frames]),h,w,3)
RuntimeError: shape '[-1, 800, 800, 3]' is invalid for input of size 58982400
该怎么解决呢？谢谢

**Comment by ashawkey** [comment]
@shangchengPKU Hi, it seems the image resolution is incorrect for your dataset (which is assumed to be 800x800 [here](https://github.com/apchenstu/TensoRF/blob/main/dataLoader/blender.py#L20)). You could modify the codebase to adapt to your settings.

**Comment by shangchengPKU** [comment]
> @shangchengPKU Hi, it seems the image resolution is incorrect for your dataset (which is assumed to be 800x800 [here](https://github.com/apchenstu/TensoRF/blob/main/dataLoader/blender.py#L20)). You could modify the codebase to adapt to your settings.

谢谢您的回复！你好，我将我的数据集重新调整为了800*800的分辨率的数据重新制作了一下，但是还是会有错误，只是这次的错误变成了如下：
lr decay 0.1 30000
Traceback (most recent call last):
  File "train.py", line 306, in <module>
    reconstruction(args)
  File "train.py", line 175, in reconstruction
    allrays, allrgbs = tensorf.filtering_rays(allrays, allrgbs, bbox_only=True)
  File "/home/shangcheng/anaconda3/envs/ccnerf/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/shangcheng/CCNeRF/models/tensorBase.py", line 336, in filtering_rays
    mask_filtered = torch.cat(mask_filtered).view(all_rgbs.shape[:-1])
RuntimeError: shape '[48000000]' is invalid for input of size 64000000
我现在怀疑是不是因为我的图片属于直接拍摄的，而不是像公共数据里面的logo那种是没有背景那种格式造成的原因，因为我的图片中带着背景了，而且我在拍摄的时候我尝试着使用的是没有拍摄顶部，只是环绕了一周360°的这种拍摄，所以到底是哪里还是存在问题呢？谢谢！
